### ISSUE TITLE
Move esbuild to peerDependencies

### ISSUE THREAD

**Issue by domsew** [esbuild-kit/core-utils#23]
Some users may prefer to install specific version of `esbuild` (e. g. the latest one). To allow this we could move `esbuild` from `dependencies` to `peerDependencies` like this:

```JSONC
{
  "dependencies": {
   // "esbuild": "~0.14.47"
  }
  "peerDependencies": {
    "esbuild": "*"
  },
  "devDependencies": {
    "esbuild": "~0.14.47"
  }
}
```

**Comment by privatenumber** [comment]
`esbuild` is in `dependencies` by design for the convenience of using `tsx` and loaders:

```sh
npx tsx ./file
```

Because it uses the semver range `~0.14.47`, you can get the latest esbuild by:
- Upgrading your direct esbuild dependency to the latest one (I believe package managers de-duplicates this)
- Running `npm update` (`pnpm update`, etc) to update sub-dependencies

The range is limited because esbuild is still in an unstable version range and can have breaking changes that may break tsx/loaders.
