### ISSUE TITLE
Why not use Build API of esbuild instead of Transform API?

### ISSUE THREAD

**Issue by AisonSu** [esbuild-kit/core-utils#9]
sometimes people may need to have a programmatic usage, such as reading the ts file on the runtime,and in that time they will need to use some feature only the Build API support, like _Inject_. and it can easily run a way like transform by stdin and other opions.Just what i say [in my PR of esbuild-register](https://github.com/egoist/esbuild-register/pull/71) ,evanw said he may remove the transform api in the future and have people use build api instand([in this esbuild issue](https://github.com/evanw/esbuild/issues/984)),so why we don't choose the powerful one?

if you agree i would contribute this feature.

**Comment by privatenumber** [comment]
tsx is designed to enhance Node.js, instead of overriding behavior and delegating it to another program.

Using the esbuild build API would prevent Node.js features such as it's resolution algorithm, and [being able to toggle it](https://github.com/esbuild-kit/esm-loader#can-it-use-nodejss-commonjs-resolution-algorithm) from working.

Besides, what you're describing sounds very simple to do via Bash pipe: `esbuild ... | node`

Not sure if I see the merit for it in a loader but if you want to abstract it into a Node.js module, you should consider a separate project for it.
